### ISSUE TITLE
Ignore outdated cached data

### ISSUE THREAD

**Issue by Procyon-b** [uso-archive/data#47] opened 2023-02-28 21:39 UTC
I think that their new site design is blocking USOa to retrieve new or updated userstyles.
Access to the previous design was still possible yesterday (forcing a cookie value), but today the "classic" version seems completely unavailable.
see https://uso.kkx.one/browse/styles?sort=created and https://uso.kkx.one/browse/styles?sort=updated

Edit: before submitting this issue I tried again on 2 computers.
Computer # 1 wasn't seeing after 24/2, computer # 2 wasn't seeing past 25/2 (9 more than # 1 when sorted by "created").
Then I forced-refreshed the pages. Now # 1 sees up to 27/2 in "created" (14 less than USO - seems correct) and # 2 hasn't changed

**Comment by Procyon-b** [comment] 2023-03-03 03:59
We are new 3/3/2023 and `https://uso.kkx.one/browse/styles?sort=created` is still showing the same most recent styles (27/02/2023).
I was hoping that the update wasn't stuck anymore, but it's apparently not the case.

Another symptom is that my latest imported style shows different metadatas depending on where it is displayed.
`https://uso.kkx.one/style/259956` shows 
```
Updated at 2/25/2023, 1:51:08 AM
Created at 2/24/2023, 2:35:55 AM
Installs this week 1
Total installs 1
```

But in `https://uso.kkx.one/browse/styles?search=%40757613` and `https://uso.kkx.one/browse/styles?search=%23userstyles.org` it appears with "6 installs" and "2/28/2023".

**Comment by 33KK** [comment] 2023-03-03 04:32
This seems to be due to CDN caching, doesn't look like there are any issues with the updater itself

**Comment by Procyon-b** [comment] 2023-03-03 16:13
Apparently. Just before your reply (and leaving the computer) I noticed that stylus had updated the userstyle to the latest. So obviously USOa was up-to-date.
I only notice these discrepancies because I regularly test my userscript ("add USOa button") against their new design.

I don't understand how they have put this design into production with so many flaws. I'm sure that they are hammering their server: they don't use thumbnails for screenshots anymore. All their cards use full-scale images. Sometimes it takes ages to load them all.

**Comment by 33KK** [comment] 2023-03-04 17:39
I mean, USOa isn't exactly a feat of engineering either, but it generally works better and i spent less than a week on it 💀 I'll probably patch it up a little more and maybe figure something out with caching, if and when i get a functional computer, since my laptop is dead right now

**Comment by Procyon-b** [comment] 2023-03-05 01:53
> I mean, USOa isn't exactly a feat of engineering either, but it generally works better and i spent less than a week on it

Nice.  :)
I'm also happy when one of my whims goes well with a speedy solution.

> since my laptop is dead right now

I know how you feel.
At least you've a temporary solution. In 2018 I had to wait 2 months before resuming my activities.

**Comment by krystian3w** [comment] 2023-06-24 11:13
Duplicate of #34

**Comment by 33KK** [comment] 2023-10-27 02:35
Hopefully didn't break anything while fixing this

**Closed as completed by 33KK** 2023-10-27 02:35 UTC
Labels: enhancement
