### ISSUE TITLE
meta-data update

### ISSUE THREAD

**Issue by Procyon-b** [uso-archive/data#34] opened 2021-06-26 13:36 UTC
When is the meta-data of the userstyle updated?
The style has been updated from us.o. But not the date, or the text ("additional info" in my case).

**Comment by krystian3w** [comment] 2021-07-25 12:04
On every 12 hours? https://github.com/33kk/uso-archive/commit/e6b49114de94e6193ec7fc14f50b760a17fb6eb1 https://github.com/33kk/uso-archive/actions/workflows/auto-update.yml

But delete may works diffrent (need manually open own issue and in "The reason given was" (on userstyles.org) add the number issue to authorization & authentication):

* https://github.com/33kk/uso-archive/search?q=158915 - still visible on page with allow Install.
   * https://uso.kkx.one/style/158915

**Comment by 33KK** [comment] 2021-07-26 01:10
I don't think there is an efficient way to get recently deleted styles from USO, currently deleted styles just stay as is.

**Comment by irajlalamoot** [comment] 2021-08-02 00:09
‫‪Marko‬‏ ***@***.***‬‏> در تاریخ دوشنبه ۲۶ ژوئیهٔ ۲۰۲۱ ساعت
۵:۴۱ نوشت:‬

**Comment by krystian3w** [comment] 2021-08-02 08:22
Unfortunately, we can't see what you wrote **irajlalamoot** (github ate characters or you sent empty mail/wrote words in wrong place so github mechanism no copied sentence to www page property).

If you can, copy the text from the old email and paste it directly on Github.

**Comment by Procyon-b** [comment] 2021-08-27 13:30
@33kk What I meant in this issue is that the meta-data is not updated when the source is updated.
The text is of the old version and the "View JSON" button displays the old version. While "Install" gives the lastest version.
Even "Updated at" is wrong.

Check `https://uso.kkx.one/style/211993`
lastest is: 0.5.0
in JSON: 0.4.99

**Comment by krystian3w** [comment] 2021-08-27 13:42
Bug on CDN level?

> https://github.com/33kk/uso-archive/blob/dbf6bb5421024bfb14e4bb7507d46468303fffc1/data/uso-styles/211993.json#L32

**Comment by Procyon-b** [comment] 2021-08-27 13:52
Oh, there is even the latest version in there.
The bug in that version is because I've used a trick with definable options to activate part of the code. The variable name is placed in the `@-moz-document regexp` . I've tested it with stylish, stylus (which has a bug now with uso options), and an older version of stylus (without the bug).
I have even tested with stylus by modifing the meta-header and adding `@preprocessor uso` and options declaration like USOa does. (not with that particular style, but a shorter one)

**edit**
I'm only assuming that the CDN bug is related.

**Comment by 33KK** [comment] 2021-08-27 14:24
Looks like a CDN caching issue 🤔
Both JSON and CSS are the same version for me

**Comment by Procyon-b** [comment] 2021-08-27 14:30
By the way, @33kk , I've played a bit with the `@preprocessor   uso` (local style to try to mimick what USOa does when it import a style with options from USO), is there a way to check the default value in a dropdown? Or is it always the first option?

> Both JSON and CSS are the same version for me

Yes, everything got updated for me too.

**Comment by Procyon-b** [comment] 2021-08-27 14:39
Another question.
Does USOa knows when the description changes on USO, or is an update of the stylesheet necessary ?

**Comment by 33KK** [comment] 2021-08-27 15:22
> Another question.
> Does USOa knows when the description changes on USO, or is an update of the stylesheet necessary ?

It scrapes recently updated page, any style update causes it to appear there

**Comment by 33KK** [comment] 2021-08-27 15:24
> By the way, @33kk , I've played a bit with the `@preprocessor uso` (local style to try to mimick what USOa does when it import a style with options from USO), is there a way to check the default value in a dropdown? Or is it always the first option?
> 
> > Both JSON and CSS are the same version for me
> 
> Yes, everything got updated for me too.

iirc stylus allows setting default values with * at the end of label, and iirc I made default entries appear first for xstyle compatibility (probably could remove it, that thing is really broken anyway)

**Comment by Procyon-b** [comment] 2021-08-27 15:35
> It scrapes recently updated page, any style update causes it to appear there

Good to know.

> iirc stylus allows setting default values with * at the end of label, and iirc I made default entries appear first for xstyle compatibility (probably could remove it, that thing is really broken anyway)

Just tried the * trick with a test style. It doesn't seem to change anything.
Moving the default value first is definitely better.

**Comment by citrusella** [comment] 2023-02-16 17:52
I dunno if this is the same issue (maybe not since it seems the inverse of something described above), but I made a few test edits--info/changelog changes, license, and in one case adding a comment to the code, but not changing functionality--to one of my userstyles (one a few days ago that didn't change its update date, and one late last night that did) specifically to see how this mirror would handle them, and it appears that the page for the style and the install page did not update, though the JSON did. 🤔

**Comment by 33KK** [comment] 2023-02-17 06:30
@citrusella that's probably due to cdn caching

**Comment by citrusella** [comment] 2023-02-17 07:48
Ah! I feel so silly! I thought the thing I'd been doing was clearing enough cache that it would be showing me nice fresh info but apparently not--I'd neglected trying to look for it in another browser or even a private window for some reason and just thought to do so around seeing this and it's showing me newer info there, so I guess this is a non-problem in my case. \*sheepishly withdraws that note*

**Comment by 33KK** [comment] 2023-06-24 02:35
Duplicate of #47

**Closed as completed by 33KK** 2023-06-24 02:36 UTC

**Comment by krystian3w** [comment] 2023-06-24 11:12
That is older...

**Comment by 33KK** [comment] 2023-06-24 17:36
> That is older...

This is my repo though, and the content of the issue is the same, the second one though happens to have a better title, which is why i kept it. I'm unsure why this matters in the first place
