### ISSUE TITLE
Incorrect license on imported styles

### ISSUE THREAD

**Issue by the-j0k3r** [uso-archive/data#24] opened 2021-02-24 10:36 UTC
Hello. I noticed some discrepancies with my work that is now on your site.

Please note https://github.com/33kk/uso-archive/blob/flomaster/data/usercss/160223.user.css, https://33kk.github.io/uso-archive/?search=inpired+dark&style=160223  this style (at least) its license has been modified from the originally intended license. it now claims NO REDISTRIBUTION

![Capture](https://user-images.githubusercontent.com/31389848/108988335-a3c89100-7694-11eb-8632-45494881c072.PNG)

The license can be seen at https://userstyles.org/styles/160223/userstyles-inspired-dark

![Capture](https://user-images.githubusercontent.com/31389848/108983744-74fbec00-768f-11eb-8798-e5984720de9f.PNG)

you can see here https://github.com/style-it-themes/userstyles-inspired-dark also properly licensed.

I am the author of said style and org owner for style-it-themes (all my USO styles are now here, which is OK), I will presume that this was some automation issue on import and request that all styles belonging to style-it-themes and myself that are in this repository be checked that they follow the intended licenses without any modifications to said licenses.

Content type: Also the styles are added a usercss metadata header and doesn't points to the repos where they belong. none of these changes follow any license terms either but I will assume its not intended to be a new style authored by someone else and that is done  to facilitate some installation direct from site, it should point to its home still. Unless my assumption is wrong.

I understand why the site exists, but if this site is modifying anything... It can do so as long as licenses are followed Im not asking for anything other than the rectification of the issues pointed out.

Thanks for your attention to this.

**Comment by 33KK** [comment] 2021-02-24 11:11
> I will presume that this was some automation issue on import

Yeah, that is the case. I'll look into it, not sure why exactly license isn't set properly. I do have ccbysa here https://github.com/33kk/uso-archive/blob/f3d04be644e82e6d8a2764c32d6ec4e5f988e86a/lib/uso.js#L55

**Comment by 33KK** [comment] 2021-02-24 11:21
> Content type: Also the styles are added a usercss metadata header and doesn't points to the repos where they belong

I could link back to userstyles.org page in the usercss file itself, but that isn't that easy, all styles will need to be reuploaded. There is a "UserStyles.org" button on the website.

**Comment by 33KK** [comment] 2021-02-24 11:35
It seems like the reason is that style didn't fit the criteria for full download (this was done because uso is extremely slow) and uso doesn't include the license in [search api responses](https://raw.githubusercontent.com/33kk/uso-archive/flomaster/data/uso-styles/160223.json)

**Comment by the-j0k3r** [comment] 2021-02-24 12:07
> It seems like the reason is that style didn't fit the criteria for full download (this was done because uso is extremely slow) and uso doesn't include the license in [search api responses](https://raw.githubusercontent.com/33kk/uso-archive/flomaster/data/uso-styles/160223.json)

Weird because 

https://github.com/33kk/uso-archive/blob/583dbbe2a14d032ef8579ef886d8c6b80ea6ecfc/data/uso-styles/160316.json#L6-L12

also one of mine, license seems to be undisturbed https://github.com/style-it-themes/gitter-inspired-dark

**Comment by 33KK** [comment] 2021-02-24 12:19
That is user default license, style specific one is in the root json object

**Comment by the-j0k3r** [comment] 2021-02-24 12:34
> That is user default license, style specific one is in the root json object

Both are ccbysa in thats style. anyway only trying to figure it out why one and not the other, settings uso side are the same for both styles.

>I could link back to userstyles.org page in the usercss file itself, but that isn't that easy, all styles will need to be reuploaded. There is a "UserStyles.org" button on the website.

I meant the actual styles home, the github org would be OK too.

thanks for reply though will wait for resolution.

**Comment by 33KK** [comment] 2021-02-24 13:02
> I meant the actual styles home, the github org would be OK too.

I could set it to style author homepage with fallback to userstyles page

> Both are ccbysa in thats style. anyway only trying to figure it out why one and not the other, settings uso side are the same for both styles.

There is no license key for the style itself in search api responses, thats why. I could set it to default user license but that could lead to styles with "No Redistribution" being marked as CC-BY-*, which would be a bigger issue.

**Comment by the-j0k3r** [comment] 2021-02-24 14:27
>There is no license key for the style itself in search api responses, thats why

Yes you have said this, yet one lic is modified the other not when the conditions are the same api wise, so one was filled in right the other not, So to me its over my head. Its not important for me to understand why the issue happened only thats its corrected.

You could try to scrape the license field without any api needed and the proceed with archiving or not depending on license.

> I could set it to default user license but that could lead to styles with "No Redistribution" being marked as CC-BY-*, which would be a bigger issue.

if there are styles with implicit NO REDISTRIBUTION licenses in USo, by simply scrapping the userstyles and republishing a style in this archive, it is already a redistribution issue right?. Same with styles that have no license whatsoever, then in that case you most definitely cant scrape those, no license is essentially the most restrictive you can get.

Though those other licensing or lack of thereof issues with 3rd party styles, (i.e. that Im not the author of) are for their respective owners to take issue with or not with how they are handled by services like this.

Thanks again.

**Comment by 33KK** [comment] 2021-02-24 15:16
> if there are styles with implicit NO REDISTRIBUTION licenses in USo, by simply scrapping the userstyles and republishing a style in this archive, it is already a redistribution issue right?. Same with styles that have no license whatsoever, then in that case you most definitely cant scrape those, no license is essentially the most restrictive you can get.

Well yes, but putting it under a permissive license is still worse. I just don't want everything to be lost in case userstyles.org fully dies. If someone is not okay with that they can ask me to remove the style.

> Yes you have said this, yet one lic is modified the other not when the conditions are the same api wise

Conditions not being the same is exactly where the issue is. It isn't that easy to fix.

**Comment by mikhoul** [comment] 2021-02-24 15:37
> I just don't want everything to be lost in case userstyles.org fully dies

And we all know it will die soon, USO is a mess now.

If an owner of a style don't want his style listed it will just ask for the style to be removed and it will be done.

Basically it's how Archive.org works, the goal is not to profit from the work of someone else but to preserve the work.

Best Regards :octocat:

**Comment by the-j0k3r** [comment] 2021-02-24 15:59
>Basically it's how Archive.org works, the goal is not to profit from the work of someone else but to preserve the work.

Archive.org  not going around modifying licenses for archived content so not exactly how Archive.org works.
Also archive.org is not actually modifying content by adding usercss headers to userstyles to make it easier for users to install outdated styles, but there we are. Its not just an archive as its designed to replace Uso by offering installs of styles due to the usercss headers being added.

Wont Archive.org itself backup USo? I think so, https://web.archive.org/web/*/userstyles.org

But thanks for sharing your view on profitability of the works, its irrelevant for the issue though.

**Comment by 33KK** [comment] 2021-02-24 16:12
> Archive.org not going around modifying licenses for archived content so not exactly how Archive.org works.

You're talking like this was intended.

> Its not important for me to understand why the issue happened only thats its corrected.

Title of the issue says otherwise

> Wont Archive.org itself backup USo? I think so, https://web.archive.org/web/*/userstyles.org

I don't think that would work for styles with custom settings, search definitely will not work, and you probably couldn't even actually install styles

**Comment by the-j0k3r** [comment] 2021-02-24 17:10
> You're talking like this was intended.

Sorry its not intended and I presumed as much as said on my first post.

>I will presume that this was some automation issue on import and ...
___
> I don't think that would work for styles with custom settings, search definitely will not work, and you probably couldn't even actually install styles

You are probably right, I must explain my motivation to become an author rather than a user and hence by extension the request to fix the issue here presented.

USo styles annoyed the hell out of me as a user because if some style had some issues and were reported, more than half the time were unresponsive by author many not even replying to emails, many are also unlicensed which meant I couldn't just use their style and fix it myself and publishing the alterations even by giving credits to main author, some styles in USo are clones with additions of restricted content. I vowed (to myself) that my styles would have support links and while on active development, that users could report issues directly to the author as opposed to the disaster of Uso. Hence the open licenses,

As an author that no longer develops USo hosted styles and do not support what USo stands for hence me and other authros left Uso, my concern is that users of my styles provided there and by extension here, will be using outdated styles that are probably broken and this isn't reflected as a notice (maybe a suggestion, on possible improvement for the future), but if users want to fix styles obtained from here, I want them to know its OK because license shown is correct.

Nothing else concerns me about this project where my styles are concerned, I see that this project offers some value to a subset of users.

I also see many efforts out there that have created viable alternatives to USo, for instance https://userstyles.world/
source at https://github.com/vednoc/userstyles.world

That design is perfect for authors based on git repositories and a design I fully support.

**Comment by 33KK** [comment] 2021-02-24 17:27
> my concern is that users of my styles provided there and by extension here, will be using outdated styles that are probably broken and this isn't reflected as a notice

Just add the notice in style description and/or title on USo, maybe also wrap it in `<mark></mark>`

**Comment by the-j0k3r** [comment] 2021-04-06 06:19
Is this being looked at or just shelved?

**Comment by 33KK** [comment] 2021-04-06 06:59
@the-j0k3r i currently don't have much free time and this isn't easy to fix, I'll probably need to redownload a lot of styles or something

**Comment by 33KK** [comment] 2021-04-19 02:53
:eyes: https://i.shx.gg/kOHYye.png

```
❯ du -h ./data --max-depth=1
950M	./data/usercss
14G	./data/screenshots
1,1G	./data/uso-styles
1,1G	./data/styles
17G	./data
```

ah yes

**Comment by 33KK** [comment] 2021-04-20 10:25
Should be fully fixed now

**Closed as completed by 33KK** 2021-04-20 10:25 UTC
Labels: bug

**Comment by the-j0k3r** [comment] 2021-04-20 10:38
Thanks

**Comment by ferdnyc** [comment] 2021-05-04 18:59
> ```
> ❯ du -h ./data --max-depth=1
> 950M	./data/usercss
> 14G	./data/screenshots
> 1,1G	./data/uso-styles
> 1,1G	./data/styles
> 17G	./data
> ```
> 
> ah yes

@33kk 

Mmm, that Pure prompt character. :drooling_face:  

Looking at that crazy screenshots-dir size, you might be able to get some real win out of pointing [imgbot](https://github.com/marketplace/imgbot) at the repo and letting it go to town. It defaults to lossless compression and other invisible optimizations, is pretty much totally automatic, and just opens up a PR to optimize all of the images when it's done.

**Comment by 33KK** [comment] 2021-05-04 21:59
@ferdnyc I already optimized everything with pngquant and jpegopti(or something like that), I doubt that it will help
